

CREATE DATABASE FBASE;

USE FBASE;

------------------------------------------------------------------
CREATE TABLE CONFIG (
  `KEY` VARCHAR(10) NOT NULL,
	VALUE VARCHAR(10) DEFAULT NULL,
	PROFILE VARCHAR(10) DEFAULT NULL,
  PRIMARY KEY (`KEY`)
);
------------------------------------------------------------------
CREATE TABLE SEQUENCE_TABLE (
  SEQ_NAME VARCHAR(10) NOT NULL,
	ALPHA_NUM_YN VARCHAR(1) DEFAULT 'N',
	ALPHA_PART VARCHAR(10) DEFAULT NULL,
	NUMERIC_PART INT(10) NOT NULL,
  PRIMARY KEY (SEQ_NAME)
);
------------------------------------------------------------------
CREATE TABLE MESSAGES (
  CODE INT(10) NOT NULL,
	MODULE VARCHAR(10) DEFAULT NULL,
	MESSAGE VARCHAR(100) DEFAULT NULL,
  PRIMARY KEY (CODE)
);
------------------------------------------------------------------
CREATE TABLE ZIPCODES (
  ZIP_CODE INT(6) NOT NULL,
	STATE VARCHAR(30) DEFAULT NULL,
	DISTRICT VARCHAR(30) DEFAULT NULL,
  COUNTRY VARCHAR(30) DEFAULT NULL,
  POST VARCHAR(30) DEFAULT NULL,
  PRIMARY KEY (ZIP_CODE)
);
------------------------------------------------------------------
CREATE TABLE USER_DETAILS (
  USERNAME VARCHAR(20) NOT NULL,
	PASSWORD VARCHAR(50) NOT NULL,
	NAME VARCHAR(50) NOT NULL,
  ROLE VARCHAR(10) NOT NULL,
  STATUS VARCHAR(1) NOT NULL,
  CREATION_DATE	DATE,
  PRIMARY KEY (USERNAME)
);
------------------------------------------------------------------
CREATE TABLE FAMILY (
  FAMILY_ID VARCHAR(20) NOT NULL,
	FAMILY_NAME	VARCHAR(50) DEFAULT NULL,
  ADDRESS_LINE1	VARCHAR(50) DEFAULT NULL,
  ADDRESS_LINE2	VARCHAR(50) DEFAULT NULL,
  ADDRESS_LINE3	VARCHAR(50) DEFAULT NULL,
  STATE	VARCHAR(30) DEFAULT NULL,
  DISTRICT VARCHAR(30) DEFAULT NULL,
  COUNTRY	VARCHAR(30) DEFAULT NULL,
  ZIP_CODE	INT(6) DEFAULT 0,
  STATUS	VARCHAR(1)  DEFAULT NULL,
  PRIMARY KEY (FAMILY_ID)
);
------------------------------------------------------------------
CREATE TABLE FAMILY_MEMBERS (
  MEMBER_ID VARCHAR(20) NOT NULL,
  FAMILY_ID	VARCHAR(20) NOT NULL,
  NAME VARCHAR(50) NOT NULL,
  DOB DATE DEFAULT NULL,
  SEX	VARCHAR(1) NOT NULL,
  BLOOD_GROUP	VARCHAR(10) DEFAULT NULL,
  MARITAL_STATUS	VARCHAR(1) DEFAULT NULL,
  CONTACT_NO	VARCHAR(20) DEFAULT NULL,
  EMAIL	VARCHAR(100) DEFAULT NULL,
  QUALIFICATION	VARCHAR(30) DEFAULT NULL,
  OCCUPATION	VARCHAR(30) DEFAULT NULL,
  ANNUAL_INCOME	INT(10) DEFAULT 0,
  FATHER_NAME	VARCHAR(50) DEFAULT NULL,
  MOTHER_NAME	VARCHAR(50) DEFAULT NULL, 
  SPOUSE_NAME	VARCHAR(50) DEFAULT NULL,
  RELATION	VARCHAR(10) DEFAULT NULL,
  FAMILY_HEAD_YN	VARCHAR(1) NOT NULL,
  DISABLED_YN	VARCHAR(1) DEFAULT 'N',
  VOTER_ID	VARCHAR(20) DEFAULT NULL,
  AADHAR_ID	VARCHAR(20) DEFAULT NULL,
  STATUS	VARCHAR(1)  DEFAULT NULL,
  PRIMARY KEY (MEMBER_ID),
  FOREIGN KEY (FAMILY_ID) REFERENCES FAMILY(FAMILY_ID)
);
------------------------------------------------------------------

	
